### PR TITLE
Upstream update and other fixes

### PR DESCRIPTION
**Pull request by cryptofuture**
I merged some upstream updates, some updates from 2.0 branch, fix noyubikey-exporter and some messages. Also missed "close database dialog" was some kind of regression (fixed now, sorry for that).
I tested things and builds available in my [ppa](https://launchpad.net/~hda-me/+archive/ubuntu/keepassx2-yubico) as always.
P.S: I can't create pull request in yubikey branch.

### CODE REVIEW

**Comment by TheZ3ro** [comment]
Any news?

**Comment by cryptofuture** [comment]
@TheZ3ro  you can use rehttps://github.com/cryptofuture/keepassx or you can fork it yourself
I don't think they will merge yubikey support in former keepassx, earlier then in next century.

**Comment by kylemanna** [comment]
Haven't had a chance to review.  Likely I'll only sync-up major releases.  The upstream project is largely silent.

**Comment by TheZ3ro** [comment]
@kylemanna check out https://github.com/keepassxreboot/keepassx seems a new fork (that is in active development)

**Comment by kylemanna** [comment]
Thanks for the heads-up @TheZ3ro, we'll see if that fork stands the test of time.

**Comment by TheZ3ro** [comment]
Sad that an opensource project that is so important lack of organization and main contributors.
Anyway I forgot to Thank you for your work :wink:

**Comment by kylemanna** [comment]
Being a project maintainer is many times a thankless job.  If the maintainers rush and merge bad code, people risk data loss and negative outcries.  If their free time is consumed by real life, people don't get updates and it generates the same negative outcries.

At least with open source, the project has the option to fork and live on. I don't fault the upstream maintainers as I don't have the time to commit to keep projects afloat any better then they do.

**Comment by kylemanna** [comment]
@cryptofuture You may be interested in https://github.com/keepassxreboot/keepassxc/pull/127 which has updates and Yubikey support.

**Comment by kylemanna** [comment]
Closing pull request in favor of https://github.com/keepassxreboot/keepassxc being the best path forward.

**Comment by cryptofuture** [comment]
Thats fast, I wanted to suggest you to close it (after notification), but you closed it faster.
I don't like keepassxc, quite amateur fork, as i think. Through it could be complied without web support, I just don't want to mess with keepassxc. I just backported your work in keepassx master in separate repository some time ago, and slowly merging into it, time after time.

**Comment by TheZ3ro** [comment]
@cryptofuture Why you don't like KeePassXC? Pretty rude calling it amateur fork without even a motivation

**Pull request closed without merging**
